services:
- mongodb
dist: trusty
language: nodejs
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_ea482d0fbc94_key -iv $encrypted_ea482d0fbc94_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
deploy:
  provider: script
  script: bash scripts/deploy.sh production
  on:
    branch: master
