services:
- mongodb
dist: trusty
language: nodejs
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
script: bash scripts/run-tests.sh
branches:
  only:
    - master
deploy:
  provider: script
  script: bash scripts/deploy.sh production
  on:
    branch: master
before_script:
  - npm i
