services:
- mongodb
dist: trusty
language: nodejs
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_ea482d0fbc94_key -iv $encrypted_ea482d0fbc94_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy.key # this key should have push access
  - ssh-add .travis/deploy.key
  - ssh-keyscan kvstage.cloud >> ~/.ssh/known_hosts
  - git remote add deploy dokku@kvstage.cloud:holdopen
  - git config --global push.default simple
  - git push deploy master
